# Generated by Django 3.1.2 on 2020-10-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seoProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=150)),
                ('project_type', models.CharField(max_length=150)),
                ('project_manager', models.CharField(max_length=150)),
                ('client', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
    ]
