# Generated by Django 3.1.2 on 2020-10-26 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pbnlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=150)),
                ('built', models.CharField(max_length=5)),
                ('builder', models.CharField(max_length=10)),
            ],
        ),
    ]
