# Generated by Django 3.1.2 on 2020-10-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pbnlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='pbn_url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('sitebuilt', models.CharField(max_length=50)),
                ('pointed', models.CharField(max_length=50)),
                ('indexfile', models.CharField(max_length=50)),
                ('builder', models.CharField(max_length=50)),
            ],
        ),
    ]
