# Generated by Django 3.1.2 on 2020-10-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pbn_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='seowebmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50)),
                ('titletag', models.CharField(max_length=50)),
                ('metadescription', models.CharField(max_length=50)),
                ('H1', models.CharField(max_length=50)),
                ('primarykw', models.CharField(max_length=50)),
                ('pagetype', models.CharField(max_length=50)),
            ],
        ),
    ]
