# Generated by Django 3.1.2 on 2020-10-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pbn_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='seowebmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('title_tag', models.CharField(max_length=60)),
                ('meta_description', models.CharField(max_length=160)),
                ('H1', models.CharField(max_length=100)),
                ('primary_kw', models.CharField(max_length=50)),
                ('page_type', models.CharField(max_length=50)),
            ],
        ),
    ]
